### PR TITLE
Add QBMS

### PR DESCRIPTION
**Pull request by khaled-alshamaa**
https://icarda-git.github.io/QBMS/

### CODE REVIEW

**Review by jpiaskowski — CHANGES_REQUESTED** [review]
Thank you for the package suggestion. Please update as thus and submit a new PR. 

> - `r pkg("QBMS")` provides functions to query [BrAPI](https://brapi.org/)-compliant databases with additional functionality for the [GIGWA](https://southgreen.fr/content/gigwa) platform.

**Comment by khaled-alshamaa** [comment]
Done!

**Review by khaled-alshamaa — COMMENTED** [review]
> Thank you for the package suggestion. Please update as thus and submit a new PR.
> 
> > * `r pkg("QBMS")` provides functions to query [BrAPI](https://brapi.org/)-compliant databases with additional functionality for the [GIGWA](https://southgreen.fr/content/gigwa) platform.

@jpiaskowski, I did the requested change :-)

**Comment by jpiaskowski** [comment]
updating QBMS

**Pull request merged**
